### ISSUE TITLE
Crate is not supported in web workers due to js-snippets usage 

### ISSUE THREAD

**Issue by Zageron** [MattiasBuelens/wasm-streams#13]
https://rustwasm.github.io/docs/wasm-bindgen/reference/js-snippets.html

Any way you'd be able to remove reliance on js-snippets?

**Comment by MattiasBuelens** [comment]
Thanks for reporting!

It looks like there's only a single usage of JavaScript snippets: https://github.com/MattiasBuelens/wasm-streams/blob/3960e8bd6836a9fb822fdb433bcd66379a732251/src/readable/into_underlying_byte_source.rs#L34-L37

This was used to work around [a bug in Chrome](https://crbug.com/1187774) when they first shipped readable byte streams, see https://github.com/MattiasBuelens/wasm-streams/commit/67bb2a413bc3ba2ff8de0a4a18fbb0e3ac59899b. Fortunately, that bug has since been fixed, so I think it's time to remove the workaround. I'll get to it! 🙂

**Comment by Zageron** [comment]
Thanks very much. @MattiasBuelens
